version: "3.3"  # optional since v1.27.0
services:
  telebot:
    container_name: telebot
    build: ./telegram_bot
    ports:
      - "80:80"
    volumes:
      - ./telegram_bot:/app
    environment:
#      - ENV=DEV
      - ENV=PROD
    networks:
      - finance-adviser-network

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
#      - ENV=DEV
      - ENV=PROD
    networks:
      - finance-adviser-network

  nginx:
    container_name: nginx
    image: nginx:1.17
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    networks:
      - finance-adviser-network


networks:
  finance-adviser-network:
    driver: bridge
