version: "3.3"  # optional since v1.27.0
services:
  telebot:
    container_name: telebot
    build: ./telegram_bot
    ports:
      - "8443:8443"
    volumes:
      - ./telegram_bot:/app
    environment:
      - ENV=PROD
    networks:
      - finance-adviser-network

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENV=PROD
    networks:
      - finance-adviser-network

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.17
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    networks:
      - finance-adviser-network

networks:
  finance-adviser-network:
    driver: bridge
