version: "3.3"  # optional since v1.27.0
services:
  telebot:
    container_name: telebot
    build: ./telegram_bot
    ports:
      - "8443:8443"
    volumes:
      - ./telegram_bot:/app
    environment:
      - ENV=DEV
      - TELEGRAM_TOKEN=1807367222:AAEKm-q_Qi3UtTrMvKbYDH5xDIQG9W7AYQQ
    networks:
      - finance-adviser-network

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - ENV=DEV
    networks:
      - finance-adviser-network


networks:
  finance-adviser-network:
    driver: bridge
