version: "3.9"  # optional since v1.27.0
services:
  telebot:
    container_name: telebot
    build: ./telegram_bot
    ports:
      - "80:80"
    volumes:
      - ./telegram_bot:/app
    environment:
#      - ENV=DEV
      - ENV=PROD

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
#      - ENV=DEV
      - ENV=PROD

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl

